version: '3.2'
services:
  db:
    image: mysql
    container_name: mysql_stock_control
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" 
    volumes:
      - stock_control_data:/var/lib/mysql

volumes:
  stock_control_data:

